final List<String> departments = [
  "Information Technology Edu.",
  "Mathematics Edu.",
  "Accounting Studies",
  "Mang. Studies",
  "Construction & Wood Tech. Edu.",
  "Auto & Mechanical Tech. Edu.",
  "Electrical & Electronics Tech. Edu.",
  "Catering & Hospitality Edu.",
  "Fashion & Textiles Design Edu.",
  "Languages Edu.",
  "Interdisciplinary Studies",
  "Crop and Soil Science Edu.",
  "Animal Science Edu.",
  "Agric. Eco. & Extension Edu.",
  "Agric Engin. & Mechanization Edu.",
  "Integrated Science Edu.",
  "Biological Science Edu.",
  "Chemistry Edu.",
  "Env. Health & Sanitation Edu.",
  "Public Health Edu.",
  "Educational Leadership",
  "Educational Studies",
];
